import type { Metadata } from "next";
import localFont from "@next/font/local";
import "./globals.css";
import AppWrapper from "./_app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const verdana = localFont({
  src: [
    {
      path: "../../public/assets/fonts/verdana/verdana.ttf",
      weight: "400",
    },
    {
      path: "../../public/assets/fonts/verdana/verdana-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-verdana",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${verdana.variable} font-verdana`}>
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
